// elements.js
const ELEMENTS = [
  // Row 1
  { atomicNumber: 1,  symbol: "H",  name: "Hydrogen", row: 1, column: 1,  category: "diatomic nonmetal", state: "gas" },
  { atomicNumber: 2,  symbol: "He", name: "Helium",   row: 1, column: 18, category: "noble", state: "gas" },

  // Row 2
  { atomicNumber: 3,  symbol: "Li", name: "Lithium",  row: 2, column: 1,  category: "alkali", state: "solid" },
  { atomicNumber: 4,  symbol: "Be", name: "Beryllium",row: 2, column: 2,  category: "alkaline-earth", state: "solid" },
  { atomicNumber: 5,  symbol: "B",  name: "Boron",    row: 2, column: 13, category: "metalloid", state: "solid" },
  { atomicNumber: 6,  symbol: "C",  name: "Carbon",   row: 2, column: 14, category: "polyatomic nonmetal", state: "solid" },
  { atomicNumber: 7,  symbol: "N",  name: "Nitrogen", row: 2, column: 15, category: "diatomic nonmetal", state: "gas" },
  { atomicNumber: 8,  symbol: "O",  name: "Oxygen",   row: 2, column: 16, category: "diatomic nonmetal", state: "gas" },
  { atomicNumber: 9,  symbol: "F",  name: "Fluorine", row: 2, column: 17, category: "halogen", state: "gas" },
  { atomicNumber: 10, symbol: "Ne", name: "Neon",     row: 2, column: 18, category: "noble", state: "gas" },

  // Row 3
  { atomicNumber: 11, symbol: "Na", name: "Sodium",   row: 3, column: 1,  category: "alkali", state: "solid" },
  { atomicNumber: 12, symbol: "Mg", name: "Magnesium",row: 3, column: 2,  category: "alkaline-earth", state: "solid" },
  { atomicNumber: 13, symbol: "Al", name: "Aluminium",row: 3, column: 13, category: "post-transition", state: "solid" },
  { atomicNumber: 14, symbol: "Si", name: "Silicon",  row: 3, column: 14, category: "metalloid", state: "solid" },
  { atomicNumber: 15, symbol: "P",  name: "Phosphorus",row:3, column:15, category: "polyatomic nonmetal", state: "solid" },
  { atomicNumber: 16, symbol: "S",  name: "Sulfur",   row: 3, column: 16, category: "polyatomic nonmetal", state: "solid" },
  { atomicNumber: 17, symbol: "Cl", name: "Chlorine", row: 3, column: 17, category: "halogen", state: "gas" },
  { atomicNumber: 18, symbol: "Ar", name: "Argon",    row: 3, column: 18, category: "noble", state: "gas" },

  // Row 4
  { atomicNumber: 19, symbol: "K",  name: "Potassium",row: 4, column: 1,  category: "alkali", state: "solid" },
  { atomicNumber: 20, symbol: "Ca", name: "Calcium",  row: 4, column: 2,  category: "alkaline-earth", state: "solid" },
  { atomicNumber: 21, symbol: "Sc", name: "Scandium", row: 4, column: 3,  category: "transition", state: "solid" },
  { atomicNumber: 22, symbol: "Ti", name: "Titanium", row: 4, column: 4,  category: "transition", state: "solid" },
  { atomicNumber: 23, symbol: "V",  name: "Vanadium", row: 4, column: 5,  category: "transition", state: "solid" },
  { atomicNumber: 24, symbol: "Cr", name: "Chromium", row: 4, column: 6,  category: "transition", state: "solid" },
  { atomicNumber: 25, symbol: "Mn", name: "Manganese",row: 4, column: 7,  category: "transition", state: "solid" },
  { atomicNumber: 26, symbol: "Fe", name: "Iron",     row: 4, column: 8,  category: "transition", state: "solid" },
  { atomicNumber: 27, symbol: "Co", name: "Cobalt",   row: 4, column: 9,  category: "transition", state: "solid" },
  { atomicNumber: 28, symbol: "Ni", name: "Nickel",   row: 4, column: 10, category: "transition", state: "solid" },
  { atomicNumber: 29, symbol: "Cu", name: "Copper",   row: 4, column: 11, category: "transition", state: "solid" },
  { atomicNumber: 30, symbol: "Zn", name: "Zinc",     row: 4, column: 12, category: "transition", state: "solid" },
  { atomicNumber: 31, symbol: "Ga", name: "Gallium",  row: 4, column: 13, category: "post-transition", state: "solid" },
  { atomicNumber: 32, symbol: "Ge", name: "Germanium",row: 4, column: 14, category: "metalloid", state: "solid" },
  { atomicNumber: 33, symbol: "As", name: "Arsenic",  row: 4, column: 15, category: "metalloid", state: "solid" },
  { atomicNumber: 34, symbol: "Se", name: "Selenium", row: 4, column: 16, category: "polyatomic nonmetal", state: "solid" },
  { atomicNumber: 35, symbol: "Br", name: "Bromine",  row: 4, column: 17, category: "halogen", state: "liquid" },
  { atomicNumber: 36, symbol: "Kr", name: "Krypton",  row: 4, column: 18, category: "noble", state: "gas" },

  // Row 5
  { atomicNumber: 37, symbol: "Rb", name: "Rubidium", row: 5, column: 1,  category: "alkali", state: "solid" },
  { atomicNumber: 38, symbol: "Sr", name: "Strontium",row: 5, column: 2,  category: "alkaline-earth", state: "solid" },
  { atomicNumber: 39, symbol: "Y",  name: "Yttrium",  row: 5, column: 3,  category: "transition", state: "solid" },
  { atomicNumber: 40, symbol: "Zr", name: "Zirconium",row: 5, column: 4,  category: "transition", state: "solid" },
  { atomicNumber: 41, symbol: "Nb", name: "Niobium",  row: 5, column: 5,  category: "transition", state: "solid" },
  { atomicNumber: 42, symbol: "Mo", name: "Molybdenum",row:5,column:6, category: "transition", state: "solid" },
  { atomicNumber: 43, symbol: "Tc", name: "Technetium",row:5,column:7, category: "transition", state: "solid" },
  { atomicNumber: 44, symbol: "Ru", name: "Ruthenium",row: 5, column: 8, category: "transition", state: "solid" },
  { atomicNumber: 45, symbol: "Rh", name: "Rhodium",  row: 5, column: 9, category: "transition", state: "solid" },
  { atomicNumber: 46, symbol: "Pd", name: "Palladium",row: 5, column: 10, category: "transition", state: "solid" },
  { atomicNumber: 47, symbol: "Ag", name: "Silver",   row: 5, column: 11, category: "transition", state: "solid" },
  { atomicNumber: 48, symbol: "Cd", name: "Cadmium",  row: 5, column: 12, category: "transition", state: "solid" },
  { atomicNumber: 49, symbol: "In", name: "Indium",   row: 5, column: 13, category: "post-transition", state: "solid" },
  { atomicNumber: 50, symbol: "Sn", name: "Tin",      row: 5, column: 14, category: "post-transition", state: "solid" },
  { atomicNumber: 51, symbol: "Sb", name: "Antimony", row: 5, column: 15, category: "metalloid", state: "solid" },
  { atomicNumber: 52, symbol: "Te", name: "Tellurium",row: 5, column: 16, category: "metalloid", state: "solid" },
  { atomicNumber: 53, symbol: "I",  name: "Iodine",   row: 5, column: 17, category: "halogen", state: "solid" },
  { atomicNumber: 54, symbol: "Xe", name: "Xenon",    row: 5, column: 18, category: "noble", state: "gas" },

  // Row 6
  { atomicNumber: 55, symbol: "Cs", name: "Cesium",   row: 6, column: 1,  category: "alkali", state: "solid" },
  { atomicNumber: 56, symbol: "Ba", name: "Barium",   row: 6, column: 2,  category: "alkaline-earth", state: "solid" },
  { atomicNumber: 57, symbol: "La–Lu", name: "Lanthanides", row: 6, column: 3, category: "placeholder", state: "unknown" },
  { atomicNumber: 72, symbol: "Hf", name: "Hafnium",  row: 6, column: 4,  category: "transition", state: "solid" },
  { atomicNumber: 73, symbol: "Ta", name: "Tantalum", row: 6, column: 5,  category: "transition", state: "solid" },
  { atomicNumber: 74, symbol: "W",  name: "Tungsten", row: 6, column: 6,  category: "transition", state: "solid" },
  { atomicNumber: 75, symbol: "Re", name: "Rhenium",  row: 6, column: 7,  category: "transition", state: "solid" },
  { atomicNumber: 76, symbol: "Os", name: "Osmium",   row: 6, column: 8,  category: "transition", state: "solid" },
  { atomicNumber: 77, symbol: "Ir", name: "Iridium",  row: 6, column: 9,  category: "transition", state: "solid" },
  { atomicNumber: 78, symbol: "Pt", name: "Platinum", row: 6, column: 10, category: "transition", state: "solid" },
  { atomicNumber: 79, symbol: "Au", name: "Gold",     row: 6, column: 11, category: "transition", state: "solid" },
  { atomicNumber: 80, symbol: "Hg", name: "Mercury",  row: 6, column: 12, category: "transition", state: "liquid" },
  { atomicNumber: 81, symbol: "Tl", name: "Thallium", row: 6, column: 13, category: "post-transition", state: "solid" },
  { atomicNumber: 82, symbol: "Pb", name: "Lead",     row: 6, column: 14, category: "post-transition", state: "solid" },
  { atomicNumber: 83, symbol: "Bi", name: "Bismuth",  row: 6, column: 15, category: "post-transition", state: "solid" },
  { atomicNumber: 84, symbol: "Po", name: "Polonium", row: 6, column: 16, category: "metalloid", state: "solid" },
  { atomicNumber: 85, symbol: "At", name: "Astatine", row: 6, column: 17, category: "halogen", state: "solid" },
  { atomicNumber: 86, symbol: "Rn", name: "Radon",    row: 6, column: 18, category: "noble", state: "gas" },

  // Row 7
  { atomicNumber: 87, symbol: "Fr", name: "Francium", row: 7, column: 1,  category: "alkali", state: "solid" },
  { atomicNumber: 88, symbol: "Ra", name: "Radium",   row: 7, column: 2,  category: "alkaline-earth", state: "solid" },
  { atomicNumber: 89, symbol: "Ac–Lr", name: "Actinides", row: 7, column: 3, category: "placeholder", state: "unknown" },
  { atomicNumber: 104,symbol: "Rf", name: "Rutherfordium",row:7,column:4, category: "transition", state: "solid" },
  { atomicNumber: 105,symbol: "Db", name: "Dubnium",  row: 7, column: 5,  category: "transition", state: "solid" },
  { atomicNumber: 106,symbol: "Sg", name: "Seaborgium",row:7,column:6, category: "transition", state: "solid" },
  { atomicNumber: 107,symbol: "Bh", name: "Bohrium",  row: 7, column: 7,  category: "transition", state: "solid" },
  { atomicNumber: 108,symbol: "Hs", name: "Hassium",  row: 7, column: 8,  category: "transition", state: "solid" },
  { atomicNumber: 109,symbol: "Mt", name: "Meitnerium",row:7,column:9, category: "transition", state: "unknown" },
  { atomicNumber: 110,symbol: "Ds", name: "Darmstadtium",row:7,column:10, category: "transition", state: "unknown" },
  { atomicNumber: 111,symbol: "Rg", name: "Roentgenium",row:7,column:11, category: "transition", state: "unknown" },
  { atomicNumber: 112,symbol: "Cn", name: "Copernicium",row:7,column:12, category: "transition", state: "unknown" },
  { atomicNumber: 113,symbol: "Nh", name: "Nihonium", row:7,column:13, category: "post-transition", state: "unknown" },
  { atomicNumber: 114,symbol: "Fl", name: "Flerovium",row: 7, column: 14, category: "post-transition", state: "unknown" },
  { atomicNumber: 115,symbol: "Mc", name: "Moscovium",row: 7, column: 15, category: "post-transition", state: "unknown" },
  { atomicNumber: 116,symbol: "Lv", name: "Livermorium",row:7,column:16, category: "post-transition", state: "unknown" },
  { atomicNumber: 117,symbol: "Ts", name: "Tennessine",row: 7, column: 17, category: "halogen", state: "unknown" },
  { atomicNumber: 118,symbol: "Og", name: "Oganesson", row: 7, column: 18, category: "noble", state: "unknown" },

  // Row 8 is blank (spacer)

  // Row 9 — Lanthanides (La → Lu) starting col 3
  { atomicNumber: 57, symbol: "La", name: "Lanthanum", row: 9, column: 3, category: "lanthanide", state: "solid" },
  { atomicNumber: 58, symbol: "Ce", name: "Cerium", row: 9, column: 4, category: "lanthanide", state: "solid" },
  { atomicNumber: 59, symbol: "Pr", name: "Praseodymium", row: 9, column: 5, category: "lanthanide", state: "solid" },
  { atomicNumber: 60, symbol: "Nd", name: "Neodymium", row: 9, column: 6, category: "lanthanide", state: "solid" },
  { atomicNumber: 61, symbol: "Pm", name: "Promethium", row: 9, column: 7, category: "lanthanide", state: "solid" },
  { atomicNumber: 62, symbol: "Sm", name: "Samarium", row: 9, column: 8, category: "lanthanide", state: "solid" },
  { atomicNumber: 63, symbol: "Eu", name: "Europium", row: 9, column: 9, category: "lanthanide", state: "solid" },
  { atomicNumber: 64, symbol: "Gd", name: "Gadolinium", row: 9, column: 10, category: "lanthanide", state: "solid" },
  { atomicNumber: 65, symbol: "Tb", name: "Terbium", row: 9, column: 11, category: "lanthanide", state: "solid" },
  { atomicNumber: 66, symbol: "Dy", name: "Dysprosium", row: 9, column: 12, category: "lanthanide", state: "solid" },
  { atomicNumber: 67, symbol: "Ho", name: "Holmium", row: 9, column: 13, category: "lanthanide", state: "solid" },
  { atomicNumber: 68, symbol: "Er", name: "Erbium", row: 9, column: 14, category: "lanthanide", state: "solid" },
  { atomicNumber: 69, symbol: "Tm", name: "Thulium", row: 9, column: 15, category: "lanthanide", state: "solid" },
  { atomicNumber: 70, symbol: "Yb", name: "Ytterbium", row: 9, column: 16, category: "lanthanide", state: "solid" },
  { atomicNumber: 71, symbol: "Lu", name: "Lutetium", row: 9, column: 17, category: "lanthanide", state: "solid" },

  // Row 10 — Actinides (Ac → Lr) starting col 3
  { atomicNumber: 89, symbol: "Ac", name: "Actinium", row: 10, column: 3, category: "actinide", state: "solid" },
  { atomicNumber: 90, symbol: "Th", name: "Thorium", row: 10, column: 4, category: "actinide", state: "solid" },
  { atomicNumber: 91, symbol: "Pa", name: "Protactinium", row: 10, column: 5, category: "actinide", state: "solid" },
  { atomicNumber: 92, symbol: "U",  name: "Uranium", row: 10, column: 6, category: "actinide", state: "solid" },
  { atomicNumber: 93, symbol: "Np", name: "Neptunium", row: 10, column: 7, category: "actinide", state: "solid" },
  { atomicNumber: 94, symbol: "Pu", name: "Plutonium", row: 10, column: 8, category: "actinide", state: "solid" },
  { atomicNumber: 95, symbol: "Am", name: "Americium", row: 10, column: 9, category: "actinide", state: "solid" },
  { atomicNumber: 96, symbol: "Cm", name: "Curium", row: 10, column: 10, category: "actinide", state: "solid" },
  { atomicNumber: 97, symbol: "Bk", name: "Berkelium", row: 10, column: 11, category: "actinide", state: "solid" },
  { atomicNumber: 98, symbol: "Cf", name: "Californium", row: 10, column: 12, category: "actinide", state: "solid" },
  { atomicNumber: 99, symbol: "Es", name: "Einsteinium", row: 10, column: 13, category: "actinide", state: "solid" },
  { atomicNumber: 100,symbol: "Fm", name: "Fermium", row: 10, column: 14, category: "actinide", state: "solid" },
  { atomicNumber: 101,symbol: "Md", name: "Mendelevium", row: 10, column: 15, category: "actinide", state: "solid" },
  { atomicNumber: 102,symbol: "No", name: "Nobelium", row: 10, column: 16, category: "actinide", state: "solid" },
  { atomicNumber: 103,symbol: "Lr", name: "Lawrencium", row: 10, column: 17, category: "actinide", state: "solid" }
];

export default ELEMENTS;
