"""constrain course title and owner uniqueness

Revision ID: 5753c3a94b97
Revises: c749667dcc5d
Create Date: 2025-08-04 13:49:56.004828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5753c3a94b97'
down_revision: Union[str, Sequence[str], None] = 'c749667dcc5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_course_title', ['owner_id', 'title'])
        batch_op.create_foreign_key('fk_courses_owner_id', 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_courses_owner_id', type_='foreignkey')
        batch_op.drop_constraint('unique_user_course_title', type_='unique')

    # ### end Alembic commands ###
