"""add level, price, is_published, video, image to Course

Revision ID: 77dcecd978be
Revises: 7f04f8f75b23
Create Date: 2025-09-04 17:06:49.404011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77dcecd978be'
down_revision: Union[str, Sequence[str], None] = '7f04f8f75b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('preview_video_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('image_url')
        batch_op.drop_column('preview_video_url')
        batch_op.drop_column('is_published')
        batch_op.drop_column('price')
        batch_op.drop_column('level')
        batch_op.drop_column('language')

    # ### end Alembic commands ###
